### ISSUE TITLE
If you don't put -Xmx32m -Xss256k the memory usage jumps to 126.242.648 B

### ISSUE THREAD

**Issue by Swadish** [dsyer/spring-boot-memory-blog#2]
![image](https://user-images.githubusercontent.com/11995252/28050203-872c95f4-65d2-11e7-884d-fadea1bb57d2.png)

Is that right? Why does Java uses so much memory?

**Comment by dsyer** [comment]
That question is not really in scope for this project. There are many reasons why Java processes consume heap, and if you don't constrain it with `-Xmx...` there's no reason for it not to use as much as it likes. The point here is that a vanilla Spring Boot app does not need to (on its own) use a huge heap.
