### ISSUE TITLE
Repeat for 1.5.x and 2.x.x

### ISSUE THREAD

**Issue by ctoestreich** [dsyer/spring-boot-memory-blog#3]
Wondering if there were any plans to do an additional memory profile or re-analysis using either the 1.5.x or 2.x.x branches to see how much optimization or degradation of footprint there has been over the last 2 years?

**Comment by glyn** [comment]
@dsyer Repeating the analysis could also take into account the changes in [Java buildpack v4](https://cloudfoundry.org/just-released-java-buildpack-4-0/) (and memory calculator v2).

**Comment by dsyer** [comment]
I added some notes on measurements I took with 1.5.9 and 2.0.0 snapshots. I think the buildpack changes would be better analysed in https://github.com/dsyer/cf-memory-tests.

**Comment by glyn** [comment]
Thanks Dave. Raised https://github.com/dsyer/cf-memory-tests/issues/1.
